import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/layout/Header'
import classNames from 'classnames'
import Footer from '@/components/layout/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  template: {
    default: '$s | Infoperformance'
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={classNames(inter.className, 'text-black min-h-screen flex flex-col')}>
        <Header />
        <main className='flex-grow bg-white'>
        {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
